### ISSUE TITLE
Bug: Sidebar cannot be opened after closing

### ISSUE THREAD

**Issue by BrilliantDeviation7** [AP-Students/website#59]
There is no open icon after the sidebar is closed on any subject page (e.g. `/subject/calculus-ab`)

**Comment by JSJ9** [comment]
Does not work for Firefox, but does work with Google Chrome and Microsoft Edge

**Comment by elijah-wright** [comment]
the reason for this is because Firefox [doesn't animate `display: none`](https://bugzilla.mozilla.org/show_bug.cgi?id=1264396) as a discrete property, because it would cancel out the animation. that behavior may change with [`transition-behavior: allow-discrete`](https://developer.mozilla.org/en-US/docs/Web/CSS/transition-behavior), which will be included in Firefox 129 next week. the solution is to animate the content in the sidebar to `position: absolute`, which has issues but works across Firefox and Chromium browsers
