### ISSUE TITLE
Feature: Custom sign-in page for NextAuth sign-ins + General NextAuth Changes

### ISSUE THREAD

**Issue by alexng353** [AP-Students/website#9]
https://next-auth.js.org/configuration/pages

Discussion: 
- [x] What providers should we support (Discord, Google, etc)
		1. Google
		2. Discord
		3. Microsoft
		
		With the rest to be added later.
			i. Email & Password
			ii. Twitter
			iii. Instagram
			iv. Facebook
			v. PassKey

Tasks:
- [ ] Design - needs volunteer
- [ ] Writing Frontend - needs volunteer
- [ ] Adding Providers to NextAuth, linking NextAuth to backend - @alexng353 

Comment beneath this post if you're interested in creating this page

**Comment by alexng353** [comment]
Proposals for alternate providers (with reasons)
1. Passkey (high security passwordless alternative, mostly my opinion)
2. Microsoft (a lot of schools have school microsoft accounts)
3. Email & Password (for obvious reasons)
4. twitter/instagram/facebook (common social media platforms that we can assume people will have)

I don't know how many providers is optimal

**Comment by AlokSwaminathan** [comment]
I think Google is a must, discord is probably fine because it's so easy to set up, and email & password is also probably a must for maximum reach. 

The issue is for email and password, with NextAuth at least (as far as I am aware), is that we have to deal with encryption (hashing, salting, etc...) on our own, which is probably not worth the effort to begin with, so it can most likely be added later.

**Comment by alexng353** [comment]
> I think Google is a must, discord is probably fine because it's so easy to set up, and email & password is also probably a must for maximum reach.

Just going to go for Google, Microsoft, and Discord for now. Google & Microsoft (Outlook) would be the most common accounts that students are provided, and Discord because... AP-Students is a Discord server

**Comment by manningwu07** [comment]
Irrelevent
